services:
  db:
    image: postgres:16
    container_name: indifusion_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - indifusion_data:/var/lib/postgresql/data
    networks:
      - internal

  adminer:
    image: adminer
    container_name: indifusion_adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - internal

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: indifusion_adonis_api
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db
    networks:
      - internal

volumes:
  indifusion_data:
